### ISSUE TITLE
bug found in can.cpp file

### ISSUE THREAD

**Issue by rohanaby79** [brandonbraun653/SAM3X8E-Libraries#1]
Hey Brandon, 
In the can.cpp file, in line 314. It seems like u missed a relational or logical operator to complete that statement. 

Sincerely,
Rohan

**Comment by brandonbraun653** [comment]
Can you file this on github through the issue button??

**Comment by rohanaby79** [comment]
Ok, I will figure out how to do that.

**Comment by rohanaby79** [comment]
I am on git hub and I did hit the issue button and post this. Is that not right?

**Comment by brandonbraun653** [comment]
Oh! I didnt know github would email me!! Thanks

**Comment by rohanaby79** [comment]
yup, u r welcome.

**Comment by brandonbraun653** [comment]
I'm not sure what you are talking about. There is a flag in that if() statement.

**Comment by rohanaby79** [comment]
ohok, I dint know that u set it a true or false before that line. I assumed that it was a variable that needed a relational or logical operator for the if statement to have condition to check. I will keep checking.
